// Package doctor implements the health-check verbs ported from
// scripts/verify.sh and skills/auto-verify-install/scripts/auto-verify.sh.
// Each check returns a CheckResult; the DoctorRunner aggregates results and
// applies the requested mode (quick, deep, install-missing, fix, json).
package doctor

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"

	"github.com/bravros/bravros/cli/internal/config"
	"github.com/bravros/bravros/cli/internal/managed"
)

// Severity classifies how bad a failed check is.
type Severity string

const (
	SeverityOK      Severity = "ok"
	SeverityWarn    Severity = "warn"
	SeverityError   Severity = "error"
	SeverityCritical Severity = "critical"
)

// CheckResult is the outcome of a single health check.
type CheckResult struct {
	Name      string   `json:"name"`
	Status    Severity `json:"status"`
	Message   string   `json:"message,omitempty"`
	CanFix    bool     `json:"can_fix,omitempty"`
	FixHint   string   `json:"fix_hint,omitempty"`
	FixBinary string   `json:"fix_binary,omitempty"` // unparsed package/binary name for proposeInstalls
}

// DoctorReport is the full output from a doctor run.
type DoctorReport struct {
	Status           string        `json:"status"` // "healthy" | "degraded" | "critical"
	Checks           []CheckResult `json:"checks"`
	InstallsProposed []string      `json:"installs_proposed,omitempty"`
	RepairsApplied   []string      `json:"repairs_applied,omitempty"`
}

// RunOpts configures the doctor run.
type RunOpts struct {
	Quick          bool // skip 1Password + firecrawl checks
	Deep           bool // all checks including expensive ones
	InstallMissing bool // auto-install safe-listed tools
	Fix            bool // attempt drift repair
	JSONOutput     bool // emit JSON to stdout instead of human output
}

// Run executes the doctor checks according to opts.
func Run(opts RunOpts) (*DoctorReport, error) {
	var checks []CheckResult

	// Always-on checks.
	checks = append(checks, checkBinary("gh", "GitHub CLI")...)
	checks = append(checks, checkBinary("jq", "jq JSON processor")...)
	checks = append(checks, checkBinary("curl", "curl HTTP client")...)
	checks = append(checks, checkBinary("git", "git VCS")...)

	checks = append(checks, checkClaudeConfigDir()...)

	// Quick-mode stops here (skip 1Password + firecrawl).
	if !opts.Quick {
		checks = append(checks, checkBinary("op", "1Password CLI")...)
	}

	// Deep mode adds more intensive checks.
	if opts.Deep {
		checks = append(checks, checkBinary("node", "Node.js")...)
		checks = append(checks, checkBinary("pipx", "pipx")...)
		checks = append(checks, checkBinary("bun", "Bun JS runtime")...)
		checks = append(checks, checkBinary("minisign", "minisign")...)
	}

	// Build report.
	report := &DoctorReport{Checks: checks}
	report.Status = aggregateStatus(checks)

	// Install-missing mode.
	if opts.InstallMissing {
		proposed := proposeInstalls(checks)
		report.InstallsProposed = proposed
		if !opts.JSONOutput {
			for _, pkg := range proposed {
				fmt.Fprintf(os.Stderr, "ℹ️  install proposed: %s\n", pkg)
			}
		}
	}

	// Fix mode: rewrite managed regions in settings.json + CLAUDE.md to repair
	// drift (mirrors `bravros config sync`). User-owned content is preserved.
	if opts.Fix {
		repairs, err := applyFixes()
		if err != nil {
			return report, err
		}
		report.RepairsApplied = repairs
		if !opts.JSONOutput {
			for _, r := range repairs {
				fmt.Fprintf(os.Stderr, "🔧 repaired: %s\n", r)
			}
		}
	}

	return report, nil
}

// applyFixes rewrites managed sections in settings.json and CLAUDE.md so any
// drift in their bravros-owned regions is repaired without touching user
// content. Returns a list of human-readable repair descriptions.
func applyFixes() ([]string, error) {
	configDir := config.ConfigDir()
	settingsPath := filepath.Join(configDir, "settings.json")
	claudeMDPath := filepath.Join(configDir, "CLAUDE.md")

	if err := managed.RewriteJSONSection(settingsPath, "_bravros_version", "v3"); err != nil {
		return nil, fmt.Errorf("repair settings.json: %w", err)
	}
	syncNote := "# bravros-managed global rules\n# Edit above this block; content below is auto-generated by bravros config sync."
	if err := managed.RewriteMarkdownSection(claudeMDPath, "globalRules", syncNote); err != nil {
		return nil, fmt.Errorf("repair CLAUDE.md: %w", err)
	}
	return []string{
		"managed sections in " + settingsPath,
		"managed sections in " + claudeMDPath,
	}, nil
}

// PrintReport prints the report in human or JSON format.
func PrintReport(report *DoctorReport, jsonOutput bool) {
	if jsonOutput {
		if report.Status == "healthy" {
			// SessionStart-hook contract: zero stdout when healthy.
			return
		}
		b, _ := json.Marshal(report)
		fmt.Println(string(b))
		return
	}

	// Human output.
	for _, c := range report.Checks {
		icon := "✅"
		switch c.Status {
		case SeverityWarn:
			icon = "⚠️ "
		case SeverityError, SeverityCritical:
			icon = "❌"
		}
		msg := c.Name
		if c.Message != "" {
			msg += " — " + c.Message
		}
		fmt.Printf("%s %s\n", icon, msg)
		if c.FixHint != "" && c.Status != SeverityOK {
			fmt.Printf("   hint: %s\n", c.FixHint)
		}
	}
	if len(report.RepairsApplied) > 0 {
		fmt.Println("\nRepairs applied:")
		for _, r := range report.RepairsApplied {
			fmt.Printf("  🔧 %s\n", r)
		}
	}
	fmt.Printf("\nStatus: %s\n", report.Status)
}

// ─── individual checks ──────────────────────────────────────────────────────

// checkBinary returns a CheckResult for an external binary.
func checkBinary(name, desc string) []CheckResult {
	_, err := exec.LookPath(name)
	if err != nil {
		return []CheckResult{{
			Name:      desc,
			Status:    SeverityWarn,
			Message:   fmt.Sprintf("%q not found in PATH", name),
			CanFix:    isSafeToInstall(name),
			FixHint:   installHint(name),
			FixBinary: name,
		}}
	}
	return []CheckResult{{Name: desc, Status: SeverityOK}}
}

// checkClaudeConfigDir verifies ~/.claude exists.
func checkClaudeConfigDir() []CheckResult {
	home, _ := os.UserHomeDir()
	claudeDir := filepath.Join(home, ".claude")
	if _, err := os.Stat(claudeDir); os.IsNotExist(err) {
		return []CheckResult{{
			Name:    "~/.claude directory",
			Status:  SeverityError,
			Message: "~/.claude does not exist — run `bravros init` to bootstrap",
			CanFix:  true,
			FixHint: "bravros init",
		}}
	}
	return []CheckResult{{Name: "~/.claude directory", Status: SeverityOK}}
}

// ─── helpers ────────────────────────────────────────────────────────────────

// allowlistInstall is the safe set of tools doctor can auto-install.
// Explicitly excludes "op" (1Password) and "claude" (Anthropic CLI) — those
// require human consent.
var allowlistInstall = map[string]bool{
	"gh":       true,
	"jq":       true,
	"wget":     true,
	"curl":     true,
	"node":     true,
	"pipx":     true,
	"bun":      true,
	"minisign": true,
}

func isSafeToInstall(name string) bool {
	return allowlistInstall[name]
}

func installHint(name string) string {
	if !isSafeToInstall(name) {
		return fmt.Sprintf("install %s manually — not in auto-install allowlist", name)
	}
	if runtime.GOOS == "darwin" {
		return fmt.Sprintf("brew install %s", name)
	}
	return fmt.Sprintf("apt-get install -y %s  (or equivalent)", name)
}

func proposeInstalls(checks []CheckResult) []string {
	var out []string
	for _, c := range checks {
		if c.Status != SeverityOK && c.CanFix && c.FixBinary != "" {
			out = append(out, c.FixBinary)
		}
	}
	return out
}

func aggregateStatus(checks []CheckResult) string {
	worst := SeverityOK
	for _, c := range checks {
		switch {
		case c.Status == SeverityCritical:
			return "critical"
		case c.Status == SeverityError && worst != SeverityCritical:
			worst = SeverityError
		case c.Status == SeverityWarn && worst == SeverityOK:
			worst = SeverityWarn
		}
	}
	if worst == SeverityOK {
		return "healthy"
	}
	if worst == SeverityWarn {
		return "degraded"
	}
	return "critical"
}
