package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/bravros/bravros/cli/internal/config"
	"github.com/bravros/bravros/cli/internal/managed"
	"github.com/spf13/cobra"
)

var configCmd = &cobra.Command{
	Use:   "config",
	Short: "Read project configuration values from .kaisser.yml",
	Run: func(cmd *cobra.Command, args []string) {
		cmd.Help()
	},
}

var mergeStrategyBase string

var mergeStrategyCmd = &cobra.Command{
	Use:   "merge-strategy",
	Short: "Print the effective merge strategy for a given base branch",
	Long: `Print the effective merge strategy (squash, merge, or rebase) for the given --base branch.

Lookup ladder:
  1. merge_strategy.by_base[<base>]  — per-base override
  2. merge_strategy.into_main        — when --base is "main"
  3. merge_strategy.default          — project-wide default
  4. "merge"                         — built-in fallback (B-0200: changed from "squash")

Exits 0 in all cases; prints a single word to stdout.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		cfg, found := config.LoadBravrosConfig()
		if !found || cfg.MergeStrategy == nil {
			fmt.Println("merge")
			return nil
		}

		ms := cfg.MergeStrategy

		// 1. Per-base override.
		if ms.ByBase != nil {
			if strategy, ok := ms.ByBase[mergeStrategyBase]; ok && strategy != "" {
				fmt.Println(strategy)
				return nil
			}
		}

		// 2. into_main shorthand.
		if mergeStrategyBase == "main" && ms.IntoMain != "" {
			fmt.Println(ms.IntoMain)
			return nil
		}

		// 3. Project-wide default.
		if ms.Default != "" {
			fmt.Println(ms.Default)
			return nil
		}

		// 4. Built-in fallback (B-0200: changed from "squash" to "merge").
		fmt.Println("merge")
		return nil
	},
}

var (
	configSyncSettings string
	configSyncClaudeMD string
	configSyncDryRun   bool
)

// configSyncCmd implements `kaisser config sync` — rewrites managed sections
// in settings.json and CLAUDE.md while preserving user customisations.
var configSyncCmd = &cobra.Command{
	Use:   "sync",
	Short: "Rewrite managed sections in settings.json and CLAUDE.md (preserves user content)",
	Long: `Rewrite the kaisser-owned sections in settings.json and CLAUDE.md, leaving all
user-owned content intact.  Markers are inserted on first run; subsequent runs
update only the managed region.

JSON strategy  — sentinel key _kaisser_managed_keys tracks which top-level keys
                 kaisser owns; everything else is preserved verbatim.

Markdown strategy — HTML comment markers bracket auto-generated content:
  <!-- kaisser-managed:start <name> -->
  <!-- kaisser-managed:end <name> -->`,
	RunE: func(cmd *cobra.Command, args []string) error {
		home, err := os.UserHomeDir()
		if err != nil {
			return fmt.Errorf("cannot determine home dir: %w", err)
		}

		configDir := config.ConfigDir()

		settingsPath := configSyncSettings
		if settingsPath == "" {
			settingsPath = filepath.Join(configDir, "settings.json")
		}
		claudeMDPath := configSyncClaudeMD
		if claudeMDPath == "" {
			claudeMDPath = filepath.Join(configDir, "CLAUDE.md")
		}

		if configSyncDryRun {
			fmt.Printf("would sync managed sections in:\n  %s\n  %s\n", settingsPath, claudeMDPath)
			_ = home
			return nil
		}

		// Rewrite managed sections.  Current implementation writes placeholder
		// content to ensure markers exist; kaisser init fills in real content.
		if err := managed.RewriteJSONSection(settingsPath, "_kaisser_version", "v3"); err != nil {
			return fmt.Errorf("sync settings.json: %w", err)
		}

		syncNote := "# kaisser-managed global rules\n# Edit above this block; content below is auto-generated by kaisser config sync."
		if err := managed.RewriteMarkdownSection(claudeMDPath, "globalRules", syncNote); err != nil {
			return fmt.Errorf("sync CLAUDE.md: %w", err)
		}

		fmt.Printf("✅ synced managed sections in %s and %s\n", settingsPath, claudeMDPath)
		return nil
	},
}

// configGetCmd implements `kaisser config get <key>` — reads a single value
// from .kaisser.yml and prints it to stdout.
//
// Supported keys:
//   - skills.preserve — prints preserved skill names as space-separated list
//     (used by the bash legacy prune block in install.sh)
var configGetCmd = &cobra.Command{
	Use:   "get <key>",
	Short: "Read a single value from .kaisser.yml",
	Long: `Read a single configuration value from .kaisser.yml and print it to stdout.

Supported keys:
  skills.preserve   Print space-separated list of preserved skill directory names.
                    Returns an empty string (exit 0) when the key is unset.
                    Used by install.sh --legacy to populate the bash preserve list.

Examples:
  kaisser config get skills.preserve       # prints e.g. "graphify"
  read -ra list <<< "$(kaisser config get skills.preserve)"`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		key := args[0]
		switch key {
		case "skills.preserve":
			skills := config.PreservedSkills()
			if len(skills) > 0 {
				// Print as a single space-separated line for easy bash array expansion.
				for i, s := range skills {
					if i > 0 {
						fmt.Print(" ")
					}
					fmt.Print(s)
				}
				fmt.Println()
			}
			// Empty list → silent exit 0 (no output) — bash reads an empty string.
			return nil
		default:
			return fmt.Errorf("unknown config key %q; supported keys: skills.preserve", key)
		}
	},
}

func init() {
	mergeStrategyCmd.Flags().StringVar(&mergeStrategyBase, "base", "", "Base branch to resolve strategy for (e.g. main, homolog)")
	configCmd.AddCommand(mergeStrategyCmd)

	configSyncCmd.Flags().StringVar(&configSyncSettings, "settings", "", "Path to settings.json (default: $KAISSER_CONFIG_DIR/settings.json)")
	configSyncCmd.Flags().StringVar(&configSyncClaudeMD, "claude-md", "", "Path to CLAUDE.md (default: $KAISSER_CONFIG_DIR/CLAUDE.md)")
	configSyncCmd.Flags().BoolVar(&configSyncDryRun, "dry-run", false, "Print what would be synced without writing")
	configCmd.AddCommand(configSyncCmd)

	configCmd.AddCommand(configGetCmd)

	rootCmd.AddCommand(configCmd)
}
