package cmd

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/bravros/bravros/cli/internal/config"
	"github.com/bravros/bravros/cli/internal/managed"
	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

var configCmd = &cobra.Command{
	Use:   "config",
	Short: "Read project configuration values from .bravros/config.json",
	Run: func(cmd *cobra.Command, args []string) {
		cmd.Help()
	},
}

var mergeStrategyBase string

var mergeStrategyCmd = &cobra.Command{
	Use:   "merge-strategy",
	Short: "Print the effective merge strategy for a given base branch",
	Long: `Print the effective merge strategy (squash, merge, or rebase) for the given --base branch.

Lookup ladder:
  1. merge_strategy.by_base[<base>]  — per-base override
  2. merge_strategy.into_main        — when --base is "main"
  3. merge_strategy.default          — project-wide default
  4. "merge"                         — built-in fallback (B-0200: changed from "squash")

Exits 0 in all cases; prints a single word to stdout.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		cfg, found := config.LoadBravrosConfig()
		if !found || cfg.MergeStrategy == nil {
			fmt.Println("merge")
			return nil
		}

		ms := cfg.MergeStrategy

		// 1. Per-base override.
		if ms.ByBase != nil {
			if strategy, ok := ms.ByBase[mergeStrategyBase]; ok && strategy != "" {
				fmt.Println(strategy)
				return nil
			}
		}

		// 2. into_main shorthand.
		if mergeStrategyBase == "main" && ms.IntoMain != "" {
			fmt.Println(ms.IntoMain)
			return nil
		}

		// 3. Project-wide default.
		if ms.Default != "" {
			fmt.Println(ms.Default)
			return nil
		}

		// 4. Built-in fallback (B-0200: changed from "squash" to "merge").
		fmt.Println("merge")
		return nil
	},
}

var (
	configSyncSettings     string
	configSyncClaudeMD     string
	configSyncDryRun       bool
	configSyncSettingsOnly bool
)

// configSyncCmd implements `bravros config sync` — rewrites managed sections
// in settings.json and CLAUDE.md while preserving user customisations.
var configSyncCmd = &cobra.Command{
	Use:   "sync",
	Short: "Rewrite managed sections in settings.json and CLAUDE.md (preserves user content)",
	Long: `Rewrite the bravros-owned sections in settings.json and CLAUDE.md, leaving all
user-owned content intact.  Markers are inserted on first run; subsequent runs
update only the managed region.

JSON strategy  — sentinel key _bravros_managed_keys tracks which top-level keys
                 bravros owns; everything else is preserved verbatim.

Markdown strategy — HTML comment markers bracket auto-generated content:
  <!-- bravros-managed:start <name> -->
  <!-- bravros-managed:end <name> -->`,
	RunE: func(cmd *cobra.Command, args []string) error {
		home, err := os.UserHomeDir()
		if err != nil {
			return fmt.Errorf("cannot determine home dir: %w", err)
		}

		configDir := config.ConfigDir()

		settingsPath := configSyncSettings
		if settingsPath == "" {
			settingsPath = filepath.Join(configDir, "settings.json")
		}
		claudeMDPath := configSyncClaudeMD
		if claudeMDPath == "" {
			claudeMDPath = filepath.Join(configDir, "CLAUDE.md")
		}

		if configSyncDryRun {
			fmt.Printf("would sync managed sections in:\n  %s\n  %s\n", settingsPath, claudeMDPath)
			_ = home
			return nil
		}

		// settings.json — register the bravros SessionStart hooks (selfupdate,
		// verify-install-check) and the statusline. Entry-level merge: only
		// entries carrying "__managed_by": "bravros" are ever replaced, so the
		// user's own hooks and every unrelated key survive.
		res, err := managed.SyncClaudeSettings(settingsPath)
		if err != nil {
			return fmt.Errorf("sync settings.json: %w", err)
		}

		// --settings-only keeps the installer out of the user's global CLAUDE.md:
		// registering hooks must not append a marker block nobody asked for.
		if !configSyncSettingsOnly {
			syncNote := "# bravros-managed global rules\n# Edit above this block; content below is auto-generated by bravros config sync."
			if err := managed.RewriteMarkdownSection(claudeMDPath, "globalRules", syncNote); err != nil {
				return fmt.Errorf("sync CLAUDE.md: %w", err)
			}
		}

		out := cmd.OutOrStdout()
		switch {
		case res.Created:
			fmt.Fprintf(out, "✅ created %s with the bravros SessionStart hooks and statusline\n", settingsPath)
		case res.Changed:
			fmt.Fprintf(out, "✅ registered the bravros SessionStart hooks and statusline in %s\n", settingsPath)
			if res.BackupPath != "" {
				fmt.Fprintf(out, "   backup: %s\n", res.BackupPath)
			}
		default:
			fmt.Fprintf(out, "✅ %s already up to date\n", settingsPath)
		}
		if res.StatusLineSkipped {
			fmt.Fprintf(out, "ℹ️  left your own \"statusLine\" untouched — remove it to let bravros manage it\n")
		}
		if !configSyncSettingsOnly {
			fmt.Fprintf(out, "✅ synced managed sections in %s\n", claudeMDPath)
		}
		return nil
	},
}

// configGetCmd implements `bravros config get <key>` — reads a single value
// from .bravros/config.json and prints it to stdout.
//
// Supported keys:
//   - skills.preserve — prints preserved skill names as space-separated list
//     (used by the bash legacy prune block in install.sh)
//   - staging_branch — the two above are special-cased for their own default
//     rules; every other dotted key path is resolved generically against the
//     raw config map (see loadConfigMap / walkConfigPath).
var configGetCmd = &cobra.Command{
	Use:   "get <key>",
	Short: "Read a single value from .bravros/config.json",
	Long: `Read a single configuration value from .bravros/config.json (falling back to a
legacy .bravros.yml when present) and print it to stdout.

Supported keys:
  skills.preserve   Print space-separated list of preserved skill directory names.
                    Returns an empty string (exit 0) when the key is unset.
                    Used by install.sh --legacy to populate the bash preserve list.
  staging_branch    Print the project staging/integration branch. Falls back to
                    "homolog" when unset or when no project config exists.
  <dotted.path>     Any other dotted key path is walked generically into
                    .bravros/config.json (e.g. stack.test_runner,
                    merge_strategy.default, permanent_branches,
                    police.direct_main, police.staging_lane). A scalar prints
                    as-is; an array prints space-separated; an object prints
                    as compact JSON. Unset key or missing config → empty
                    output (exit 0). A config file that exists but does not
                    parse → "warning: .bravros/config.json is not valid JSON:
                    …" on stderr, exit 1 — so a broken config is never
                    mistaken for an unset key.

Examples:
  bravros config get skills.preserve             # prints e.g. "graphify"
  read -ra list <<< "$(bravros config get skills.preserve)"
  STAGING=$(bravros config get staging_branch)   # prints e.g. "homolog"
  bravros config get stack.test_runner           # prints e.g. "go test"
  bravros config get permanent_branches          # prints e.g. "main homolog"`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		key := args[0]
		switch key {
		case "skills.preserve":
			skills := config.PreservedSkills()
			if len(skills) > 0 {
				// Print as a single space-separated line for easy bash array expansion.
				for i, s := range skills {
					if i > 0 {
						fmt.Print(" ")
					}
					fmt.Print(s)
				}
				fmt.Println()
			}
			// Empty list → silent exit 0 (no output) — bash reads an empty string.
			return nil
		case "staging_branch":
			// LoadBravrosConfig defaults StagingBranch to "homolog" for a missing
			// config, an unset key, and an empty string alike — so the printed
			// value is always a usable branch name.
			cfg, _ := config.LoadBravrosConfig()
			branch := cfg.StagingBranch
			if branch == "" {
				branch = "homolog"
			}
			fmt.Println(branch)
			return nil
		default:
			m, err := loadConfigMap()
			if err != nil {
				// A config that exists but does not parse is NOT "unset": a
				// script reading `$(bravros config get x)` must be able to
				// tell "no value" (empty, exit 0) from "your config is broken"
				// (warning on stderr, exit 1), or a typo in config.json
				// silently turns every key into its default.
				fmt.Fprintf(cmd.ErrOrStderr(), "warning: %v\n", err)
				return err
			}
			if m == nil {
				// No config on disk (JSON or legacy) → empty output, exit 0.
				return nil
			}
			val, found := walkConfigPath(m, key)
			if !found || val == nil {
				return nil
			}
			printConfigValue(cmd.OutOrStdout(), val)
			return nil
		}
	},
	// The warning above IS the error message; without these cobra would print
	// it a second time as "Error: …" and dump the usage block under it.
	SilenceErrors: true,
	SilenceUsage:  true,
}

// loadConfigMap reads .bravros/config.json as a generic map for dotted-key
// lookups that aren't among the BravrosConfig struct's known fields (e.g. a
// "project" key nobody has modeled, or a future key added before the struct
// catches up). Falls back to a legacy .bravros.yml/.sbravros.yml when the
// JSON config is absent, matching config.LoadBravrosConfig's own fallback —
// but this is a read-only lookup: it never migrates the legacy file to disk,
// since that side effect belongs solely to config.LoadBravrosConfig (used by
// the two special-cased keys above).
//
// Three outcomes, and callers must keep them apart: (nil, nil) — no config
// file exists at all; (m, nil) — parsed; (nil, err) — a file exists but does
// not parse, err naming the file and the parser's reason.
func loadConfigMap() (map[string]any, error) {
	if data, err := os.ReadFile(config.ConfigFilename); err == nil {
		var m map[string]any
		if jErr := json.Unmarshal(data, &m); jErr != nil {
			return nil, fmt.Errorf("%s is not valid JSON: %w", config.ConfigFilename, jErr)
		}
		return m, nil
	}

	for _, legacy := range []string{config.LegacyConfigFilename, config.LegacySbravrosFilename} {
		data, err := os.ReadFile(legacy)
		if err != nil {
			continue
		}
		var m map[string]any
		if yErr := yaml.Unmarshal(data, &m); yErr != nil {
			return nil, fmt.Errorf("%s is not valid YAML: %w", legacy, yErr)
		}
		return m, nil
	}

	return nil, nil
}

// walkConfigPath descends a dotted key path (e.g. "stack.test_runner") into a
// generic JSON/YAML-decoded config map, returning the value at that path and
// whether every segment resolved to a nested object.
func walkConfigPath(m map[string]any, path string) (any, bool) {
	var cur any = m
	for _, part := range strings.Split(path, ".") {
		asMap, ok := cur.(map[string]any)
		if !ok {
			return nil, false
		}
		val, ok := asMap[part]
		if !ok {
			return nil, false
		}
		cur = val
	}
	return cur, true
}

// printConfigValue renders a generic config value the way bash scripts want
// it: a scalar as-is, an array space-separated (mirroring skills.preserve
// above), an object as compact JSON.
func printConfigValue(w io.Writer, val any) {
	switch v := val.(type) {
	case []any:
		for i, item := range v {
			if i > 0 {
				fmt.Fprint(w, " ")
			}
			fmt.Fprint(w, formatConfigScalar(item))
		}
		fmt.Fprintln(w)
	case map[string]any:
		data, err := json.Marshal(v)
		if err != nil {
			return
		}
		fmt.Fprintln(w, string(data))
	default:
		fmt.Fprintln(w, formatConfigScalar(v))
	}
}

// formatConfigScalar prints a string value without quotes and every other
// scalar (bool, number) via its default Go formatting.
func formatConfigScalar(v any) string {
	switch x := v.(type) {
	case nil:
		return ""
	case string:
		return x
	default:
		return fmt.Sprint(x)
	}
}

func init() {
	mergeStrategyCmd.Flags().StringVar(&mergeStrategyBase, "base", "", "Base branch to resolve strategy for (e.g. main, homolog)")
	configCmd.AddCommand(mergeStrategyCmd)

	configSyncCmd.Flags().StringVar(&configSyncSettings, "settings", "", "Path to settings.json (default: $BRAVROS_CONFIG_DIR/settings.json)")
	configSyncCmd.Flags().StringVar(&configSyncClaudeMD, "claude-md", "", "Path to CLAUDE.md (default: $BRAVROS_CONFIG_DIR/CLAUDE.md)")
	configSyncCmd.Flags().BoolVar(&configSyncDryRun, "dry-run", false, "Print what would be synced without writing")
	configSyncCmd.Flags().BoolVar(&configSyncSettingsOnly, "settings-only", false, "Sync settings.json only; leave CLAUDE.md untouched")
	configCmd.AddCommand(configSyncCmd)

	configCmd.AddCommand(configGetCmd)

	rootCmd.AddCommand(configCmd)
}
