package cmd

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestCheckAiSignatureBlocksMadeWithCursorOnPRCreate(t *testing.T) {
	t.Parallel()

	command := `gh pr create --base homolog --title "✨ feat: add fleet" --body "` +
		"## Summary\n\nShip the fleet slice.\n\nMade with [Cursor](https://cursor.com)" +
		`"`

	if msg := checkAiSignature(command); msg == "" {
		t.Fatal("expected Made with Cursor in a PR body to be blocked")
	} else if !strings.Contains(msg, "AI signature") {
		t.Fatalf("block message should name the signature, got %q", msg)
	}
}

func TestCheckAiSignatureBlocksMadeWithCursorOnPREdit(t *testing.T) {
	t.Parallel()

	command := `gh pr edit 5 --body "Updated notes` + "\n\n" + `Made with Cursor"`
	if msg := checkAiSignature(command); msg == "" {
		t.Fatal("expected Made with Cursor on gh pr edit to be blocked")
	}
}

func TestCheckAiSignatureBlocksGitCommitMessage(t *testing.T) {
	t.Parallel()

	command := "git commit -m " + shellDoubleQuote("✨ feat: add fleet\n\nMade with Cursor")
	if msg := checkAiSignature(command); msg == "" {
		t.Fatal("expected Made with Cursor on git commit -m to be blocked")
	}
}

func TestCheckAiSignatureAllowsCleanPRBody(t *testing.T) {
	t.Parallel()

	command := `gh pr create --base homolog --title "✨ feat: add fleet" --body "## Summary\nShip the fleet slice."`
	if msg := checkAiSignature(command); msg != "" {
		t.Fatalf("clean PR body should pass, got %q", msg)
	}
}

func TestCheckAiSignatureAllowsViaCursorDomainLanguage(t *testing.T) {
	t.Parallel()

	command := `gh pr create --title "✨ feat: paginate via cursor" --body "Resume via cursor token."`
	if msg := checkAiSignature(command); msg != "" {
		t.Fatalf("domain language must not match, got %q", msg)
	}
}

func TestCheckAiSignatureReadsBodyFile(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	path := filepath.Join(dir, "pr.md")
	if err := os.WriteFile(path, []byte("## Summary\n\nMade with [Cursor](https://cursor.com)\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	command := `gh pr create --base homolog --title "✨ feat: add fleet" --body-file ` + path
	if msg := checkAiSignature(command); msg == "" {
		t.Fatal("expected body-file containing Made with Cursor to be blocked")
	}
}

func TestPolicePreToolUseBlocksPRAttribution(t *testing.T) {
	envelope, _ := runPreToolUseComment(t, `gh pr create --title "✨ feat: add fleet" --body "Made with Cursor"`)
	if envelope.Exit != 2 {
		t.Fatalf("exitCode = %d, want 2", envelope.Exit)
	}
	if !strings.Contains(envelope.Stderr, "AI signature") {
		t.Fatalf("stderr should name the signature, got %q", envelope.Stderr)
	}
}

// ── Parity corpus ────────────────────────────────────────────────────────────
// Every form below was verified to be BLOCKED by the commit-msg hook but to
// PASS the original hand-rolled police regex, i.e. each one reached a PR body
// unblocked. police is the only gate on PR bodies, so each is a real hole.

func TestCheckAiSignatureBlocksHookParityCorpus(t *testing.T) {
	t.Parallel()

	footers := []string{
		"Co-Authored-By: Claude <noreply@anthropic.com>",
		"🤖 Generated with [Claude Code](https://claude.com/claude-code)",
		"Made with [Cursor](https://cursor.com)",
		"Made with Cursor", "Made with Gemini", "Generated with Gemini",
		"Co-authored by Claude", "Co-authored with Claude", "Co_authored_by: Claude",
		"co-author: Claude", "Assisted by Claude", "Assisted-By: Claude",
		"Written by Claude", "Authored by Claude Code", "Created with ChatGPT",
		"Reviewed by Claude", "Prompted by Claude", "With help from ChatGPT",
		"Pair-programmed with Copilot",
		"Signed-off-by: Claude <noreply@anthropic.com>",
		"Generated by an LLM", "Powered by AI",
		"Written with assistance from an AI assistant",
		"Co-Authored-By: Gemini <noreply@google.com>",
		"Co-Authored-By: Devin <devin@cognition.ai>",
		"Co-Authored-By: Windsurf <noreply@codeium.com>",
		"- Made with Cursor",
		"> Co-Authored-By: Claude <noreply@anthropic.com>",
	}

	for _, footer := range footers {
		body := "## Summary\n\nReal change.\n\n" + footer
		command := `gh pr create --title "✨ feat: x" --body ` + shellDoubleQuote(body)
		if msg := checkAiSignature(command); msg == "" {
			t.Errorf("footer reached a PR body unblocked: %q", footer)
		}
	}
}

// A PR body must be able to DOCUMENT these strings — otherwise the PR that
// ships this gate cannot describe itself. Mid-sentence prose and backticked
// quotes are legitimate; only a footer owning its own line is attribution.
func TestCheckAiSignatureAllowsDocumentationAndProse(t *testing.T) {
	t.Parallel()

	bodies := []string{
		"Records are generated with cursor-based pagination.",
		"Docs say files generated with cursor rules must be committed.",
		"Adds a guard for bodies containing Made with Cursor.",
		"Blocked examples: `Made with Cursor`, `Made with [Cursor](https://cursor.com)`.",
		"```\nCo-Authored-By: Claude <noreply@anthropic.com>\n```",
		"paginate via cursor",
		"Resume via cursor token.",
		"Co-Authored-By: Jane Doe <12345+jane@users.noreply.github.com>",
	}

	for _, body := range bodies {
		command := `gh pr create --title "✨ feat: x" --body ` + shellDoubleQuote(body)
		if msg := checkAiSignature(command); msg != "" {
			t.Errorf("legitimate body was blocked: %q\n  -> %s", body, msg)
		}
	}
}

// Fail-closed: a body the hook cannot read must be refused, not waved through.
func TestCheckAiSignatureFailsClosedOnOpaqueBody(t *testing.T) {
	t.Parallel()

	commands := []string{
		`gh pr create --title "x" --body-file -`,
		`gh pr create --title "x" --body-file /nonexistent/path/pr.md`,
		`gh pr create --title "x" --body-file <(printf 'Made with Cursor')`,
		`gh pr create --title "x" --body-file "$BODY"`,
		`git commit -F -`,
	}

	for _, command := range commands {
		if msg := checkAiSignature(command); msg == "" {
			t.Errorf("opaque body was not blocked: %q", command)
		} else if !strings.Contains(msg, "cannot read") {
			t.Errorf("expected the opaque-body reason for %q, got %q", command, msg)
		}
	}
}

// Flag shapes an exact-token comparison misses.
func TestCheckAiSignatureHandlesBundledAndGluedFlags(t *testing.T) {
	t.Parallel()

	commands := []string{
		`git commit -am ` + shellDoubleQuote("feat: x\n\nMade with Cursor"),
		`git commit -m` + shellDoubleQuote("feat: x\n\nMade with Cursor"),
		`gh pr create --body=` + shellDoubleQuote("Made with Cursor"),
		`gh pr create -b` + shellDoubleQuote("Made with Cursor"),
	}

	for _, command := range commands {
		if msg := checkAiSignature(command); msg == "" {
			t.Errorf("flag shape bypassed the gate: %q", command)
		}
	}
}

// Surfaces beyond gh pr / git commit. `gh pr merge --subject` matters most:
// a squash subject is written server-side, so no local commit-msg hook fires.
func TestCheckAiSignatureCoversAdditionalSurfaces(t *testing.T) {
	t.Parallel()

	commands := []string{
		`gh pr merge 5 --squash --subject ` + shellDoubleQuote("feat: x\n\nMade with Cursor"),
		`gh issue create --title "x" --body ` + shellDoubleQuote("Made with Cursor"),
		`gh issue comment 5 --body ` + shellDoubleQuote("Made with Cursor"),
		`gh release create v1.0.0 --notes ` + shellDoubleQuote("Made with Cursor"),
		`git tag -a v1.0.0 -m ` + shellDoubleQuote("Release\n\nMade with Cursor"),
	}

	for _, command := range commands {
		if msg := checkAiSignature(command); msg == "" {
			t.Errorf("surface not covered: %q", command)
		}
	}
}

// The repo's own canonical @claude review comment must still post.
func TestCheckAiSignatureAllowsCanonicalClaudeReviewComment(t *testing.T) {
	t.Parallel()

	body := "@claude review this PR and check if we are able to merge. " +
		"Analyze the code changes for any issues, security concerns, or improvements needed.\n\n" +
		"Required: end your review with EXACTLY ONE of these lines, as plain text, " +
		"alone on its own line, as the final line:\n\n" +
		"BRAVROS-VERDICT: approved\nBRAVROS-VERDICT: changes-requested\n\n" +
		"Do NOT wrap the line in an HTML comment, code fence, blockquote, or list item."

	command := `gh pr comment 80 --body ` + shellDoubleQuote(body)
	if msg := checkAiSignature(command); msg != "" {
		t.Fatalf("canonical @claude review comment must not be blocked, got %q", msg)
	}
}

// Backtick evasion: `Made with `Cursor`` renders as a footer but would reduce
// to "Made with " if inline spans were removed wholesale. Backtick CHARACTERS
// are stripped, the text under them is not — otherwise one backtick pair
// disables the whole gate. Fenced blocks stay exempt: that is the sanctioned
// way for a body to document these strings.
func TestCheckAiSignatureResistsBacktickEvasion(t *testing.T) {
	t.Parallel()

	blocked := []string{
		"Made with `Cursor`",
		"`Made with Cursor`",
		"Co-Authored-By: `Claude` <noreply@anthropic.com>",
		"**Made with [Cursor](https://cursor.com)**",
	}
	for _, body := range blocked {
		command := `gh pr create --title "x" --body ` + shellDoubleQuote(body)
		if msg := checkAiSignature(command); msg == "" {
			t.Errorf("backtick/markdown evasion slipped through: %q", body)
		}
	}

	fenced := "## Summary\n\nDocuments the gate:\n\n```\nMade with Cursor\nCo-Authored-By: Claude <noreply@anthropic.com>\n```\n"
	command := `gh pr create --title "x" --body ` + shellDoubleQuote(fenced)
	if msg := checkAiSignature(command); msg != "" {
		t.Errorf("fenced documentation must pass, got %q", msg)
	}
}

// Footers verified against real GitHub history, plus the two shapes the verb x
// name cross-product cannot see: session trailers (no attribution verb) and
// Cursor's agent badge, which is its ACTUAL PR attribution — an image link with
// no plain text, so a text-only gate would miss most Cursor PRs.
func TestCheckAiSignatureBlocksVerifiedVendorFooters(t *testing.T) {
	t.Parallel()

	footers := []string{
		"Made-with: Cursor",
		"Co-authored-by: Cursor Agent <cursoragent@cursor.com>",
		"Co-authored-by: copilot-swe-agent[bot] <198982749+Copilot@users.noreply.github.com>",
		"Signed-off-by: copilot-swe-agent <copilot-swe-agent@github.com>",
		"Co-authored-by: GitHub Copilot <github-copilot@users.noreply.github.com>",
		"Co-Authored-By: Devin AI <158243242+devin-ai-integration[bot]@users.noreply.github.com>",
		"Co-authored-by: factory-droid[bot] <138933559+factory-droid[bot]@users.noreply.github.com>",
		"Co-authored-by: Droid <droid@factory.ai>",
		"Co-authored-by: openhands <openhands@all-hands.dev>",
		"Co-authored-by: google-labs-jules[bot] <161369871+google-labs-jules[bot]@users.noreply.github.com>",
		"Co-Authored-By: Claude Opus 5 (1M context) <noreply@anthropic.com>",
		"Co-authored-by: Codex <noreply@openai.com>",
		"Claude-Session: https://claude.ai/code/session_abc123",
		"Copilot-Session: 4f2a1b8c-0000-4444-9999-abcdef012345",
		"[![Open in Cursor](https://cursor.com/badge.svg)](https://cursor.com/agents/abc123)",
	}

	for _, footer := range footers {
		body := "## Summary\n\nReal change.\n\n" + footer
		command := `gh pr create --title "✨ feat: x" --body ` + shellDoubleQuote(body)
		if msg := checkAiSignature(command); msg == "" {
			t.Errorf("verified vendor footer reached a PR body unblocked: %q", footer)
		}
	}
}

// The new vendor tokens must not swallow ordinary engineering vocabulary.
// "droid" is bounded so it does not fire inside "android"; "factory" is only
// ever matched as "factory-droid", because bare "factory" is everyday language
// in a codebase with factories and the factory pattern.
func TestCheckAiSignatureVendorTokensAvoidCommonWords(t *testing.T) {
	t.Parallel()

	bodies := []string{
		"Fixtures are generated by factory definitions in database/factories.",
		"The payload is generated with a factory helper.",
		"Built by the android build pipeline.",
		"Screenshots generated by android emulator runs.",
		"Co-authored-by: Jules Verne <jules@example.com>",
	}

	for _, body := range bodies {
		command := `gh pr create --title "x" --body ` + shellDoubleQuote(body)
		if msg := checkAiSignature(command); msg != "" {
			t.Errorf("common engineering language was blocked: %q\n  -> %s", body, msg)
		}
	}
}
